/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ArtStyle {
  'id' : StyleId,
  'name' : string,
  'description' : string,
  'artworks' : Array<Artwork>,
  'characteristics' : Array<string>,
  'timePeriod' : string,
  'notableArtists' : Array<string>,
}
export interface ArtStyleWithProgress {
  'progress' : [] | [StyleProgress],
  'artStyle' : ArtStyle,
  'isStudied' : boolean,
}
export interface Artwork { 'title' : string, 'artist' : string }
export interface QuizOption { 'styleId' : StyleId, 'styleName' : string }
export interface QuizQuestion {
  'clue' : string,
  'correctStyleId' : StyleId,
  'clueType' : string,
  'options' : Array<QuizOption>,
}
export interface QuizResult {
  'correctStyleId' : StyleId,
  'correct' : boolean,
  'correctStyleName' : string,
}
export type StyleId = bigint;
export interface StyleProgress {
  'attemptsCount' : bigint,
  'bestScore' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserStats {
  'stylesStudied' : bigint,
  'quizzesTaken' : bigint,
  'perStyleProgress' : Array<[StyleId, StyleProgress]>,
  'averageScore' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addArtStyle' : ActorMethod<[ArtStyle], StyleId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteArtStyle' : ActorMethod<[StyleId], undefined>,
  'getAllArtStyles' : ActorMethod<[], Array<ArtStyle>>,
  'getAllArtStylesWithProgress' : ActorMethod<[], Array<ArtStyleWithProgress>>,
  'getArtStyle' : ActorMethod<[StyleId], [] | [ArtStyle]>,
  'getCallerStats' : ActorMethod<[], UserStats>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getRandomQuizQuestion' : ActorMethod<[], [] | [QuizQuestion]>,
  'getStudiedStyles' : ActorMethod<[], Array<StyleId>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserStats' : ActorMethod<[Principal], UserStats>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markStyleAsStudied' : ActorMethod<[StyleId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitQuizAnswer' : ActorMethod<[StyleId, StyleId, bigint], QuizResult>,
  'unmarkStyleAsStudied' : ActorMethod<[StyleId], undefined>,
  'updateArtStyle' : ActorMethod<[StyleId, ArtStyle], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];