/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const StyleId = IDL.Nat;
export const Artwork = IDL.Record({ 'title' : IDL.Text, 'artist' : IDL.Text });
export const ArtStyle = IDL.Record({
  'id' : StyleId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'artworks' : IDL.Vec(Artwork),
  'characteristics' : IDL.Vec(IDL.Text),
  'timePeriod' : IDL.Text,
  'notableArtists' : IDL.Vec(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const StyleProgress = IDL.Record({
  'attemptsCount' : IDL.Nat,
  'bestScore' : IDL.Nat,
});
export const ArtStyleWithProgress = IDL.Record({
  'progress' : IDL.Opt(StyleProgress),
  'artStyle' : ArtStyle,
  'isStudied' : IDL.Bool,
});
export const UserStats = IDL.Record({
  'stylesStudied' : IDL.Nat,
  'quizzesTaken' : IDL.Nat,
  'perStyleProgress' : IDL.Vec(IDL.Tuple(StyleId, StyleProgress)),
  'averageScore' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const QuizOption = IDL.Record({
  'styleId' : StyleId,
  'styleName' : IDL.Text,
});
export const QuizQuestion = IDL.Record({
  'clue' : IDL.Text,
  'correctStyleId' : StyleId,
  'clueType' : IDL.Text,
  'options' : IDL.Vec(QuizOption),
});
export const QuizResult = IDL.Record({
  'correctStyleId' : StyleId,
  'correct' : IDL.Bool,
  'correctStyleName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addArtStyle' : IDL.Func([ArtStyle], [StyleId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteArtStyle' : IDL.Func([StyleId], [], []),
  'getAllArtStyles' : IDL.Func([], [IDL.Vec(ArtStyle)], ['query']),
  'getAllArtStylesWithProgress' : IDL.Func(
      [],
      [IDL.Vec(ArtStyleWithProgress)],
      ['query'],
    ),
  'getArtStyle' : IDL.Func([StyleId], [IDL.Opt(ArtStyle)], ['query']),
  'getCallerStats' : IDL.Func([], [UserStats], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getRandomQuizQuestion' : IDL.Func([], [IDL.Opt(QuizQuestion)], []),
  'getStudiedStyles' : IDL.Func([], [IDL.Vec(StyleId)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserStats' : IDL.Func([IDL.Principal], [UserStats], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markStyleAsStudied' : IDL.Func([StyleId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitQuizAnswer' : IDL.Func([StyleId, StyleId, IDL.Nat], [QuizResult], []),
  'unmarkStyleAsStudied' : IDL.Func([StyleId], [], []),
  'updateArtStyle' : IDL.Func([StyleId, ArtStyle], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const StyleId = IDL.Nat;
  const Artwork = IDL.Record({ 'title' : IDL.Text, 'artist' : IDL.Text });
  const ArtStyle = IDL.Record({
    'id' : StyleId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'artworks' : IDL.Vec(Artwork),
    'characteristics' : IDL.Vec(IDL.Text),
    'timePeriod' : IDL.Text,
    'notableArtists' : IDL.Vec(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const StyleProgress = IDL.Record({
    'attemptsCount' : IDL.Nat,
    'bestScore' : IDL.Nat,
  });
  const ArtStyleWithProgress = IDL.Record({
    'progress' : IDL.Opt(StyleProgress),
    'artStyle' : ArtStyle,
    'isStudied' : IDL.Bool,
  });
  const UserStats = IDL.Record({
    'stylesStudied' : IDL.Nat,
    'quizzesTaken' : IDL.Nat,
    'perStyleProgress' : IDL.Vec(IDL.Tuple(StyleId, StyleProgress)),
    'averageScore' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const QuizOption = IDL.Record({
    'styleId' : StyleId,
    'styleName' : IDL.Text,
  });
  const QuizQuestion = IDL.Record({
    'clue' : IDL.Text,
    'correctStyleId' : StyleId,
    'clueType' : IDL.Text,
    'options' : IDL.Vec(QuizOption),
  });
  const QuizResult = IDL.Record({
    'correctStyleId' : StyleId,
    'correct' : IDL.Bool,
    'correctStyleName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addArtStyle' : IDL.Func([ArtStyle], [StyleId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteArtStyle' : IDL.Func([StyleId], [], []),
    'getAllArtStyles' : IDL.Func([], [IDL.Vec(ArtStyle)], ['query']),
    'getAllArtStylesWithProgress' : IDL.Func(
        [],
        [IDL.Vec(ArtStyleWithProgress)],
        ['query'],
      ),
    'getArtStyle' : IDL.Func([StyleId], [IDL.Opt(ArtStyle)], ['query']),
    'getCallerStats' : IDL.Func([], [UserStats], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getRandomQuizQuestion' : IDL.Func([], [IDL.Opt(QuizQuestion)], []),
    'getStudiedStyles' : IDL.Func([], [IDL.Vec(StyleId)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserStats' : IDL.Func([IDL.Principal], [UserStats], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markStyleAsStudied' : IDL.Func([StyleId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitQuizAnswer' : IDL.Func(
        [StyleId, StyleId, IDL.Nat],
        [QuizResult],
        [],
      ),
    'unmarkStyleAsStudied' : IDL.Func([StyleId], [], []),
    'updateArtStyle' : IDL.Func([StyleId, ArtStyle], [], []),
  });
};

export const init = ({ IDL }) => { return []; };